experiment_name      : "AES-EXP-1"
training_filename    : "train_with_prompts.csv"
data_dir             : "./input/"
artifacts_dir        : "./output/"
output_dir           : "${artifacts_dir}/${experiment_name}"
fold                 : 0
model_id             : "microsoft/deberta-v3-xsmall"
num_labels           : 6
wandb_log            : True
wandb_project_name   : "AES"
notes                : "first note"
truncation           : True
max_length           : 512
seed                 : 2024

training_args :
  learning_rate               : 2.0e-5
  per_device_train_batch_size : 8
  per_device_eval_batch_size  : 16
  num_train_epochs            : 2
  weight_decay                : 0.01,
  evaluation_strategy         : "epoch"
  save_strategy               : "epoch"
  load_best_model_at_end      : True
  push_to_hub                 : False